### ISSUE TITLE
Add possibility to build-in counter scripts

### ISSUE THREAD

**Issue by zxqfox** [bem-contrib/stat-counters#20]
This usually needed for enterprise products.

**Comment by verybigman** [comment]
:+1:

**Comment by remnev** [comment]
Can you provide more info about issue?

**Comment by verybigman** [comment]
Enterprise public policy prohibits load modules with the code from the outside. We load it from local.

**Comment by zxqfox** [comment]
Agreed totally. Also it can be useful for CLI apps insights.

**Comment by remnev** [comment]
Is built-in solution an html code or what?

**Comment by verybigman** [comment]
this is external script. For Google Analytics is `ga.js` for us.

**Comment by remnev** [comment]
@zxqfox @awinogradov is it still actual?

**Comment by awinogradov** [comment]
No, thanks. We did on our level in custom way ;)
