### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by tadatuta** [bem-contrib/stat-counters#62]
Please refer to https://github.com/bem/bem-history/pull/48/files to provide proper ignores.

**Comment by tadatuta** [comment]
@remnev can't find it on npm: https://www.npmjs.com/package/bem-stat-counters

have you published it to external?

**Comment by remnev** [comment]
@tadatuta sorry

have done it just now https://www.npmjs.com/package/bem-stat-counters

**Comment by tadatuta** [comment]
@remnev thank you!
